[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"
numpy = "^1.22.2"
plotly = "^5.6.0"
matplotlib = "^3.5.1"
scipy = "^1.8.0"
open3d = "^0.15.2"
pygmsh = "^7.1.17"
holoviews = "^1.14.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"